apiVersion: v1
kind: Pod
metadata:
  name: escape-pod-default
  namespace: lab6
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: pwn
    image: alpine:3.20
    command: ["sleep","infinity"]
    volumeMounts:
    - name: host
      mountPath: /mnt/host
      readOnly: true
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
