apiVersion: v1
kind: Pod
metadata:
  name: escape-pod
  namespace: lab6
  labels:
    app: lab6
spec:
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
  - name: pwn
    image: alpine:3.20
    command: ["sleep","infinity"]
    securityContext:
      allowPrivilegeEscalation: true
    volumeMounts:
    - name: host
      mountPath: /mnt/host
      readOnly: true
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
