apiVersion: v1
kind: Pod
metadata:
  name: attacker-pod
  namespace: default
spec:
  containers:
  - name: attacker
    image: alpine:3.19
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
          - NET_ADMIN
          - SYS_PTRACE
    stdin: true
    tty: true
